### ISSUE TITLE
Run Clean as Cronjob?

### ISSUE THREAD

**Issue by alanman87** [l3uddz/cloudplow#27] opened 2018-07-23 05:19 UTC
How would I run the clean function as a cronjob? When I invoke the clean command manually everything works. I tried doing this as a cron and get an error with each file that it tries to delete on the remote. It looks like this:

2018-07-23 00:00:39,450 - ERROR      - rclone               - delete_file                    - Exception deleting file 'gdrive:/Media/Movies/The Last Samurai (2003)/The Last Samurai (2003) Bluray-1080p.mkv' from remote gdrive: 
Traceback (most recent call last):
  File "/opt/cloudplow/utils/rclone.py", line 37, in delete_file
    resp = process.execute(cmd, logs=False)
  File "/opt/cloudplow/utils/process.py", line 11, in execute
    stderr=subprocess.STDOUT)
  File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'rclone'

**Comment by l3uddz** [comment] 2018-09-30 12:50
The issue is its unable to launch rclone, likely because I'm not providing a full path to the binary and instead launching it as 

rclone COMMAND

I will look to add a config option to specify the rclone binary path

**Comment by l3uddz** [comment] 2018-09-30 15:54
should be resolved with the latest develop branch.

re-open issue if the problem persists

**Closed by l3uddz** 2018-09-30 15:54 UTC
